/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { AppMode } from './appMode';
import type { Github } from './github';
import type { LocalFile } from './localFile';

export interface AppConfig {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  AppMode: AppMode;
  Github: Github;
  LocalFile: LocalFile;
}
