/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface CreateDocumentInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Kind of document source (e.g., 'local', 'github') */
  kind: string;
  /** Absolute path for the new document (must end with .md) */
  path: string;
}
