/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface DeleteDocumentOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Deleted document path */
  path: string;
  /** Whether the document was deleted successfully */
  success: boolean;
}
