/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface FileInfo {
  /** Whether this is a directory */
  is_dir: boolean;
  /** File or directory name */
  name: string;
}
