/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { FileInfo } from './fileInfo';

/**
 * Files and directories in the path
 */
export type GetDirectoryOutputBodyItems = FileInfo[] | null;
