/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetDirectoryOutputBodyItems } from './getDirectoryOutputBodyItems';

export interface GetDirectoryOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Files and directories in the path */
  items: GetDirectoryOutputBodyItems;
  /** Searched directory path */
  path: string;
}
