/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { Document } from './document';

/**
 * List of documents found in the directory
 */
export type GetDocumentsOutputBodyDocuments = Document[] | null;
