/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentsOutputBodyDocuments } from './getDocumentsOutputBodyDocuments';

export interface GetDocumentsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** List of documents found in the directory */
  documents: GetDocumentsOutputBodyDocuments;
}
