/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type GetDirectoryParams = {
/**
 * Absolute path to directory
 */
path?: string;
/**
 * Kind of directory source (e.g., 'local', 'github')
 */
kind?: string;
};
