/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface GetDocumentContentOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Document content */
  content: string;
  /** Document path */
  path: string;
}
