/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */
import type { LocalFileDirectories } from './localFileDirectories';

export interface LocalFile {
  Directories: LocalFileDirectories;
}
