/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export type PutDocumentContentParams = {
/**
 * Absolute path to the document
 */
path?: string;
/**
 * Kind of document source (e.g., 'local', 'github')
 */
kind?: string;
};
