/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateDocumentContentOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Success or error message */
  message: string;
  /** Document path */
  path: string;
  /** Whether the update was successful */
  success: boolean;
}
