/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateDocumentContentInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** New content for the document */
  content: string;
}
