/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectDirectoryRouteImport } from './routes/select-directory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowsePathRouteImport } from './routes/browse.$path'

const SelectDirectoryRoute = SelectDirectoryRouteImport.update({
  id: '/select-directory',
  path: '/select-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePathRoute = BrowsePathRouteImport.update({
  id: '/browse/$path',
  path: '/browse/$path',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/select-directory': typeof SelectDirectoryRoute
  '/browse/$path': typeof BrowsePathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-directory': typeof SelectDirectoryRoute
  '/browse/$path': typeof BrowsePathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/select-directory': typeof SelectDirectoryRoute
  '/browse/$path': typeof BrowsePathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/select-directory' | '/browse/$path'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/select-directory' | '/browse/$path'
  id: '__root__' | '/' | '/select-directory' | '/browse/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelectDirectoryRoute: typeof SelectDirectoryRoute
  BrowsePathRoute: typeof BrowsePathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-directory': {
      id: '/select-directory'
      path: '/select-directory'
      fullPath: '/select-directory'
      preLoaderRoute: typeof SelectDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$path': {
      id: '/browse/$path'
      path: '/browse/$path'
      fullPath: '/browse/$path'
      preLoaderRoute: typeof BrowsePathRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelectDirectoryRoute: SelectDirectoryRoute,
  BrowsePathRoute: BrowsePathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
