name: Cloud SQL Scheduler

on:
  schedule:
    # 10:00 JST (01:00 UTC) daily
    - cron: '0 1 * * *'
    # 18:00 JST (09:00 UTC) daily
    - cron: '0 9 * * *'
    # 00:00 JST (15:00 UTC previous day) daily
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  stop-cloudsql:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_ID }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT_EMAIL }}
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Stop Cloud SQL instance
        run: |
          gcloud sql instances patch ${{ secrets.WIF_CLOUDSQL_INSTANCE_NAME }} \
            --activation-policy=NEVER \
            --quiet
        continue-on-error: true

      - uses: ./.github/workflows/notify-discord/action.yaml
        if: success()
        with:
          message: "Cloud SQL instance ${{ secrets.WIF_CLOUDSQL_INSTANCE_NAME }} stopped successfully"

      - uses: ./.github/workflows/notify-discord/action.yaml
        if: failure()
        with:
          message: "Failed to stop Cloud SQL instance ${{ secrets.WIF_CLOUDSQL_INSTANCE_NAME }} \nClick [here to view the logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?check_suite_focus=true)."
